# treefmt.nix
{ pkgs, ... }:
{
  # Used to find the project root
  projectRootFile = "flake.nix";

  # https://github.com/numtide/treefmt-nix/tree/main/programs
  # https://github.com/numtide/treefmt-nix/tree/main/examples
  programs = {
    actionlint.enable = true;
    beautysh.enable = true;
    gofmt.enable = true;
    just.enable = true;
    nixfmt.enable = true;
    prettier = {
      enable = true;
      excludes = [ "T1.md" ];

    };
    shfmt.enable = true;
    shellcheck.enable = true;
    statix.enable = true;
    terraform.enable = true;
    typos = {
      enable = true;
      # includes = [ "flake.nix" ];
    };
    yamlfmt.enable = true;
  };

  # # Override the default package
  # programs.terraform.package = pkgs.terraform_1;
  # # Override the default settings generated by the above option
  # settings.formatter.terraform.excludes = [ "hello.tf" ];
}
